site_name: Faust Libraries 
title_brand: Libraries
site_description: Faust Libraries Documentation.
copyright: Copyright &copy; 2019-2020 <a href="https://www.grame.fr">Grame-CNCM</a>

nav:
    - Overview:
         - ' Organization ':  organization.md
         - ' Standard Functions ':  standardFunctions.md
         - ' Contributing ':  contributing.md
         - ' Copyright/License ':  copyright.md
    - Index: libs/index.md
    - Libraries:
         - ' analyzers ':  libs/analyzers.md
         - ' basics ':  libs/basics.md
         - ' compressors ':  libs/compressors.md
         - ' delays ':  libs/delays.md
         - ' demos ':  libs/demos.md
         - ' dx7 ':  libs/dx7.md
         - ' envelopes ':  libs/envelopes.md
         - ' filters ':  libs/filters.md
         - ' hoa ':  libs/hoa.md
         - ' interpolators ':  libs/interpolators.md
         - ' maths ':  libs/maths.md
         - ' mi ':  libs/mi.md
         - ' misceffects ':  libs/misceffects.md
         - ' oscillators ':  libs/oscillators.md
         - ' noises ':  libs/noises.md
         - ' phaflangers ':  libs/phaflangers.md
         - ' physmodels ':  libs/physmodels.md
         - ' quantizer ':  libs/quantizer.md
         - ' reducemaps ':  libs/reducemaps.md
         - ' reverbs ':  libs/reverbs.md
         - ' routes ':  libs/routes.md
         - ' signals ':  libs/signals.md
         - ' soundfiles ':  libs/soundfiles.md
         - ' spats ':  libs/spats.md
         - ' synths ':  libs/synths.md
         - ' vaeffects ':  libs/vaeffects.md
         - ' wavedigitalfilters ':  libs/wavedigitalfilters.md
         - ' webaudio ':  libs/webaudio.md

    - About: about.md

theme: 
  name: mkdocs
  custom_dir: 'theme'
  navigation_depth: 3

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - toc:
        baselevel: 1

site_dir: ../docs


extra_css:
    - css/extra.css
    
