site_name: Faust Libraries 
site_description: Faust Libraries Documentation.
copyright: Copyright &copy; 2019-2026 <a href="https://www.grame.fr">Grame-CNCM</a>

nav:
    - Overview:
         - ' Organization ': organization.md
         - ' Standard Functions ': standardFunctions.md
         - ' Contributing ': contributing.md
         - ' Community ': community.md
         - ' Copyright/License ': about.md
    - Index: libs/index.md
    - Libraries:
         - ' antialiased ': libs/aanl.md
         - ' analyzers ': libs/analyzers.md
         - ' basics ': libs/basics.md
         - ' compressors ': libs/compressors.md
         - ' debug ': libs/debug.md
         - ' delays ': libs/delays.md
         - ' demos ': libs/demos.md
         - ' dx7/dx7 ': libs/dx7/dx7.md
         - ' dx7/env ': libs/dx7/env.md
         - ' dx7/lfo ': libs/dx7/lfo.md
         - ' dx7/operator ': libs/dx7/operator.md
         - ' dx7/pitchenv ': libs/dx7/pitchenv.md
         - ' envelopes ': libs/envelopes.md
         - ' fds ': libs/fds.md
         - ' filters ': libs/filters.md
         - ' hoa ': libs/hoa.md
         - ' hysteresis ': libs/hysteresis.md
         - ' interpolators ': libs/interpolators.md
         - ' linearalgebra ': libs/linearalgebra.md
         - ' maths ': libs/maths.md
         - ' mi ': libs/mi.md
         - ' misceffects ': libs/misceffects.md
         - ' motion ': libs/motion.md
         - ' noises ': libs/noises.md
         - ' oscillators ': libs/oscillators.md
         - ' phaflangers ': libs/phaflangers.md
         - ' physmodels ': libs/physmodels.md
         - ' quantizers ': libs/quantizers.md
         - ' reducemaps ': libs/reducemaps.md
         - ' reverbs ': libs/reverbs.md
         - ' routes ': libs/routes.md
         - ' signals ': libs/signals.md
         - ' soundfiles ': libs/soundfiles.md
         - ' spats ': libs/spats.md
         - ' synths ': libs/synths.md
         - ' vaeffects ': libs/vaeffects.md
         - ' version ': libs/version.md
         - ' wdmodels ': libs/wdmodels.md
         - ' webaudio ': libs/webaudio.md

    - About: about.md

theme: 
  name: mkdocs
  custom_dir: 'theme'
  navigation_depth: 3

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - toc:
        baselevel: 1

site_dir: ../site


extra_css:
    - css/extra.css
    
